name: gromacs_py
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - gromacs=2019.1
  - ambertools=20.9
  - rdkit=2020.09.5
  - jupyter
  - nglview
  - pip
  - pip:
    - gromacs_py
    - git+https://github.com/alanwilter/acpype.git
    - simpletraj
    - tqdm
    - seaborn
