name: gromacs_py
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - gromacs=2018.5
  - ambertools=20.9
  - rdkit=2020.09.5
  - pip
  - pip:
    - git+https://github.com/alanwilter/acpype.git
